export const webRoutes = {
  home: '/',
  login: '/login',
  logout: '/logout',
  Dashboard: '/Dashbord',
  Vente: '/Vente',
  Achat: '/Achat',
  Facture: '/Facture',
  Fournisseur: '/Fournisseur',
  Produit: '/Produit',  
  SingleProduit: '/Produit/:id',
  Commandes: '/Commandes',
  Clients: '/Clients',
  Caisse: '/Caisse',
  Stock: '/Stock',
  Marque: '/Marque',
  Parametre: '/Parametre',
  Societe: '/Société',
  stagnant: '/stagnant',

};
